### ISSUE TITLE
General  Cleanup

### ISSUE THREAD

**Issue by Nepo26** [norwoodj/helm-docs#182]
After some time with the repository abandoned we needed to revamp by making it more active and fixing old bugs.

## Verify PRs
Check every PR from old to new to see its current relevance and gracefully close every single one of them.

- [x] https://github.com/norwoodj/helm-docs/pull/106
- [x] https://github.com/norwoodj/helm-docs/pull/144
- [x] https://github.com/norwoodj/helm-docs/pull/150
- [x] https://github.com/norwoodj/helm-docs/pull/159
- [x] https://github.com/norwoodj/helm-docs/pull/161
- [x] https://github.com/norwoodj/helm-docs/pull/167
- [x] https://github.com/norwoodj/helm-docs/pull/172
- [x] https://github.com/norwoodj/helm-docs/pull/176
- [x] https://github.com/norwoodj/helm-docs/pull/178
  - It seems to be an okay complaint and easy fix. So just accepted it. The deploy didn't finish but it can be fixed after reviewing another PR.

## Verify Issues
- [x] Categorize issues using Labels
- [ ] Fix bug issues
- [ ] Go through feature issues to see relevance to be done and categorize accordingly
